// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AddressList: typeof import('./components/AddressList/index.vue')['default']
    AffixBarAction: typeof import('./components/AffixBarAction/index.vue')['default']
    AppProvider: typeof import('./components/AppProvider/index.tsx')['default']
    AreaField: typeof import('./components/AreaField/index.vue')['default']
    Captcha: typeof import('./components/Captcha/index.vue')['default']
    Copyright: typeof import('./components/Copyright/index.tsx')['default']
    ExchangeCoupon: typeof import('./components/ExchangeCoupon/index.vue')['default']
    GoodCard: typeof import('./components/GoodCard/index.vue')['default']
    IconPayFail: typeof import('./components/icons/IconPayFail.vue')['default']
    IconPaySuccess: typeof import('./components/icons/IconPaySuccess.vue')['default']
    MineSvgWaveBg: typeof import('./components/MineSvgWaveBg/index.vue')['default']
    Plate: typeof import('./components/Plate/index.vue')['default']
    Price: typeof import('./components/Price/index.vue')['default']
    ProList: typeof import('./components/ProList/index.vue')['default']
    PwdField: typeof import('./components/PwdField/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sku: typeof import('./components/Sku/index.vue')['default']
    SpainList: typeof import('./components/SpainList/index.vue')['default']
    Tabbar: typeof import('./components/Tabbar/index.vue')['default']
    Upload: typeof import('./components/Upload/index.vue')['default']
  }
}
