// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AddressList: typeof import('./components/AddressList/index.vue')['default']
    AffixBar: typeof import('./components/AffixBar/index.vue')['default']
    AppClientInfoPopup: typeof import('./components/AppClientInfoPopup/index.vue')['default']
    AppInfiniteScroller: typeof import('./components/AppInfiniteScroller/index.tsx')['default']
    AppList: typeof import('./components/AppList/index.tsx')['default']
    AppProvider: typeof import('./components/AppProvider/index.tsx')['default']
    AppWindowBar: typeof import('./components/AppWindowBar/index.vue')['default']
    AreaField: typeof import('./components/AreaField/index.vue')['default']
    CaptchaCodeField: typeof import('./components/CaptchaCodeField/index.vue')['default']
    CaptchaPopup: typeof import('./components/CaptchaPopup/index.vue')['default']
    Copyright: typeof import('./components/Copyright/index.tsx')['default']
    Demo: typeof import('./components/AppInfiniteScroller/demo/index.vue')['default']
    FunctionCall: typeof import('./components/AppClientInfoPopup/functionCall.tsx')['default']
    GoodCard: typeof import('./components/GoodCard/index.vue')['default']
    Home: typeof import('./components/ProList/demo/home/index.vue')['default']
    IconDark: typeof import('./components/icons/IconDark.vue')['default']
    IconPayFail: typeof import('./components/icons/IconPayFail.vue')['default']
    IconPaySuccess: typeof import('./components/icons/IconPaySuccess.vue')['default']
    IconSkin: typeof import('./components/icons/IconSkin.vue')['default']
    MineSvgWaveBg: typeof import('./components/MineSvgWaveBg/index.vue')['default']
    Plate: typeof import('./components/Plate/index.vue')['default']
    Price: typeof import('./components/Price/index.vue')['default']
    ProList: typeof import('./components/ProList/index.vue')['default']
    PwdField: typeof import('./components/PwdField/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sku: typeof import('./components/Sku/index.vue')['default']
    SpainList: typeof import('./components/SpainList/index.vue')['default']
    Tabbar: typeof import('./components/Tabbar/index.vue')['default']
    UploadAvatar: typeof import('./components/UploadAvatar/index.vue')['default']
  }
}
